name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 liblua5.4-dev make

      - name: Build
        run: |
          make -C src/

      - name: Run tests
        run: |
          lua test/leregex_test.lua

      - name: Run check
        run: |
          make check

      - name: Run distcheck
        run: |
          make distcheck

